# Generated by Django 4.1.7 on 2023-09-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smileKonect', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('TZS', 'TZS'), ('$', 'USD')], default='R', max_length=100),
        ),
    ]
