# Generated by Django 4.1.7 on 2023-09-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smileKonect', '0005_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
