# Generated by Django 4.1.7 on 2023-09-27 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smileKonect', '0006_rename_settings_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('Dar es salaam', 'Dar es salaam'), ('Arusha', 'Arusha'), ('Morogoro', 'Morogoro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='province',
            field=models.CharField(blank=True, choices=[('Dar es salaam', 'Dar es salaam'), ('Arusha', 'Arusha'), ('Morogoro', 'Morogoro')], max_length=100),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
